# Generated by Django 4.0.4 on 2024-02-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AlterField(
            model_name='performance',
            name='theatre_hall',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='theatre.theatrehall'),
        ),
        migrations.AlterField(
            model_name='play',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
