# Generated by Django 4.0.4 on 2024-02-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "theatre",
            "0002_alter_ticket_options_alter_performance_theatre_hall_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="performance",
            name="theatre_hall",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="theatre.theatrehall",
            ),
            preserve_default=False,
        ),
    ]
